---
- hosts: localhost
  connection: local
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: 12bucket-1
      aws_access_key: AKIA36PG34ATC2GKMDMS
      aws_secret_key: 2zngrYtw0KF+KHzzdl9ekPGzLMMzX1Btducb6i+z
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: 12bucket-1
         type: example
         policy: 
           {
             "Version": "2012-10-17",
             "Id": "Policy1673355763950",
             "Statement": [
               {
                 "Sid": "Stmt1673355761438",
                 "Effect": "Allow",
                 "Principal": {
                   "AWS": "arn:aws:iam::821359796262:user/msuser"
                   },
                 "Action": "s3:*",
                 "Resource": "arn:aws:s3:::12bucket-1/msuser"
               } 
             ]
           }
