---
- hosts: localhost
  connection: local
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: qwertybucket
      aws_access_key: AKIA36PG34ATC2GKMDMS
      aws_secret_key: 2zngrYtw0KF+KHzzdl9ekPGzLMMzX1Btducb6i+z
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: qwertybucket
         type: example
      policy: "
        {
    "Version": "2012-10-17",
    "Statement": [
       {
          "Sid": "statement1",
          "Effect": "Allow",
          "Principal": {
             "AWS": "arn:aws:iam::821359796262:user/msuser"
          },
          "Action": [
             "s3:GetBucketLocation",
             "s3:ListBucket"
          ],
          "Resource": [
             "arn:aws:s3:::qwertybucket/msuser"
          ]
       },
       {
          "Sid": "statement2",
          "Effect": "Allow",
          "Principal": {
             "AWS": "arn:aws:iam::821359796262:user/msuser"
          },
          "Action": [
              "s3:GetObject"
          ],
          "Resource": [
             "arn:aws:s3:::qwertybucket/msuser"
          ]
        }
      ]
    }" 

  
