---
- hosts: localhost
  connection: local
  #gather_facts: False
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: 1234bucket
      aws_access_key: AKIA36PG34ATBCKXIIEO
      aws_secret_key: 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
      state: present
      region: ap-south-1
      #permission: private # acl: public-read
      #policy: "{{ lookup('file','my_bucket_policy.json') }}"
      #requester_pays: true
      versioning: no
      tags:
         name: 1234bucket
         type: example
  - name: create policy
  {
    "Version": "2012-10-17",
    "Statement": [
       {
          "Sid": "statement1",
          "Effect": "Allow",
          "Principal": {
             "AWS": "arn:aws:iam::821359796262:user/msuser"
          },
          "Action": [
             "s3:GetBucketLocation",
             "s3:ListBucket"
          ],
          "Resource": [
             "arn:aws:s3:::1234bucket/msuser"
          ]
       },
       {
          "Sid": "statement2",
          "Effect": "Allow",
          "Principal": {
             "AWS": "arn:aws:iam::821359796262:user/msuser"
          },
          "Action": [
              "s3:GetObject"
          ],
          "Resource": [
             "arn:aws:s3:::1234bucket/msuser"
          ]
       }
    ]
 }
