---
- hosts: localhost
  connection: local
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: 1234bucket
      aws_access_key: AKIA36PG34ATC2GKMDMS
      aws_secret_key: 2zngrYtw0KF+KHzzdl9ekPGzLMMzX1Btducb6i+z
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: 1234bucket
         type: example
  
