- hosts: localhost
  gather_facts: false

  tasks:
    - amazon.aws.s3_bucket:
        name: "<16bucket-1>"
        state: present
        public_access:
          BlockPublicAcls: true
          # IgnorePublicAcls: false
          # BlockPublicPolicy: false
          # RestrictPublicBuckets: false
      register: module_result

    - debug:
        var: module_result


